export const designTokens = {
  colors: {
    background: 'var(--color-background)',
    surface: 'var(--color-surface)',
    surfaceElevated: 'var(--color-surface-elevated)',
    foreground: 'var(--color-foreground)',
    muted: 'var(--color-muted)',
    mutedForeground: 'var(--color-muted-foreground)',
    border: 'var(--color-border)',
    borderSubtle: 'var(--color-border-subtle)',
    primary: 'var(--color-primary)',
    primaryForeground: 'var(--color-primary-foreground)',
    primaryMuted: 'var(--color-primary-muted)',
    secondary: 'var(--color-secondary)',
    secondaryForeground: 'var(--color-secondary-foreground)',
    accent: 'var(--color-accent)',
    accentForeground: 'var(--color-accent-foreground)',
    success: 'var(--color-success)',
    successForeground: 'var(--color-success-foreground)',
    successMuted: 'var(--color-success-muted)',
    warning: 'var(--color-warning)',
    warningForeground: 'var(--color-warning-foreground)',
    warningMuted: 'var(--color-warning-muted)',
    error: 'var(--color-error)',
    errorForeground: 'var(--color-error-foreground)',
    errorMuted: 'var(--color-error-muted)',
    info: 'var(--color-info)',
    infoForeground: 'var(--color-info-foreground)',
    infoMuted: 'var(--color-info-muted)',
    ring: 'var(--color-ring)',
    overlay: 'var(--color-overlay)',
  },
  spacing: {
    xs: 'var(--spacing-xs)',
    sm: 'var(--spacing-sm)',
    md: 'var(--spacing-md)',
    lg: 'var(--spacing-lg)',
    xl: 'var(--spacing-xl)',
    '2xl': 'var(--spacing-2xl)',
    '3xl': 'var(--spacing-3xl)',
  },
  typography: {
    fontFamily: 'var(--font-family-sans)',
    fontSizeSm: 'var(--font-size-sm)',
    fontSizeMd: 'var(--font-size-md)',
    fontSizeLg: 'var(--font-size-lg)',
    lineHeight: 'var(--line-height-base)',
  },
  radius: {
    sm: 'var(--radius-sm)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    full: 'var(--radius-full)',
  },
  shadows: {
    sm: 'var(--shadow-sm)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
  },
  breakpoints: {
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
    '2xl': '1536px',
  },
  zIndex: {
    base: 'var(--z-base)',
    dropdown: 'var(--z-dropdown)',
    modal: 'var(--z-modal)',
    toast: 'var(--z-toast)',
    'route-transition': 'var(--z-route-transition)',
  },
  animation: {
    durationFast: 'var(--duration-fast)',
    durationNormal: 'var(--duration-normal)',
    durationSlow: 'var(--duration-slow)',
    easingDefault: 'var(--easing-default)',
    easingIn: 'var(--easing-in)',
    easingOut: 'var(--easing-out)',
  },
} as const;

export type DesignTokens = typeof designTokens;

/** CSS variable names for runtime theme injection. */
export const cssVariableNames = {
  color: [
    '--color-background',
    '--color-surface',
    '--color-surface-elevated',
    '--color-foreground',
    '--color-muted',
    '--color-muted-foreground',
    '--color-border',
    '--color-border-subtle',
    '--color-primary',
    '--color-primary-foreground',
    '--color-primary-muted',
    '--color-secondary',
    '--color-secondary-foreground',
    '--color-accent',
    '--color-accent-foreground',
    '--color-success',
    '--color-success-foreground',
    '--color-success-muted',
    '--color-warning',
    '--color-warning-foreground',
    '--color-warning-muted',
    '--color-error',
    '--color-error-foreground',
    '--color-error-muted',
    '--color-info',
    '--color-info-foreground',
    '--color-info-muted',
    '--color-ring',
    '--color-overlay',
  ],
  spacing: [
    '--spacing-xs',
    '--spacing-sm',
    '--spacing-md',
    '--spacing-lg',
    '--spacing-xl',
    '--spacing-2xl',
    '--spacing-3xl',
  ],
} as const;
