/**
 * Simulated menu catalog for browse UI (mock datasource only).
 */

import 'server-only';

import type { Locale } from '@/config/site';
import type {
  MenuCategory,
  MenuItem,
  MenuLabel,
  MenuSpicyLevel,
} from '@/repositories/menu/menu.types';

type Localized = Record<Locale, string>;

type Seed = {
  code: string;
  name: Localized;
  description: Localized;
  taste: Localized;
  category: MenuCategory;
  ingredients: Localized[];
  price: number;
  rating: number;
  calories: number;
  protein: number;
  prepMinutes: number;
  spicyLevel: MenuSpicyLevel;
  labels: MenuLabel[];
  imageUrl: string;
};

const img = (id: string, w = 900) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${String(w)}&q=80`;

const seeds: Seed[] = [
  {
    code: 'BF-001',
    name: {
      en: 'Tamago rice bowl',
      fa: 'کاسه برنج تاماگو',
      de: 'Tamago-Reisbowl',
      ar: 'وعاء أرز التاماغو',
    },
    description: {
      en: 'Soft egg over seasoned rice with nori and sesame.',
      fa: 'تخم‌مرغ نرم روی برنج مزه‌دار با نوری و کنجد.',
      de: 'Weiches Ei auf gewürztem Reis mit Nori und Sesam.',
      ar: 'بيض طري فوق أرز متبّل مع نوري وسمسم.',
    },
    taste: {
      en: 'Silky, savory, gently sweet',
      fa: 'ابریشمی، شورِ ملایم، کمی شیرین',
      de: 'Seidig, herzhaft, leicht süß',
      ar: 'حريري، مالح بلطف، حلو خفيف',
    },
    category: 'breakfast',
    ingredients: [
      { en: 'Egg', fa: 'تخم‌مرغ', de: 'Ei', ar: 'بيض' },
      { en: 'Rice', fa: 'برنج', de: 'Reis', ar: 'أرز' },
      { en: 'Nori', fa: 'نوری', de: 'Nori', ar: 'نوري' },
      { en: 'Sesame', fa: 'کنجد', de: 'Sesam', ar: 'سمسم' },
    ],
    price: 14,
    rating: 4.8,
    calories: 420,
    protein: 18,
    prepMinutes: 12,
    spicyLevel: 0,
    labels: ['chefChoice'],
    imageUrl: img('photo-1604908176997-125f25cc6f3d'),
  },
  {
    code: 'SN-002',
    name: {
      en: 'Edamame with sea salt',
      fa: 'ادامامه با نمک دریا',
      de: 'Edamame mit Meersalz',
      ar: 'إدامامي بملح البحر',
    },
    description: {
      en: 'Warm pods, flaky salt, a squeeze of yuzu.',
      fa: 'غلاف‌های گرم، نمک پولکی، کمی یوزو.',
      de: 'Warme Schoten, Flockensalz, ein Spritzer Yuzu.',
      ar: 'قرون دافئة، ملح خشن، رشة يوزو.',
    },
    taste: {
      en: 'Clean, bright, lightly citrus',
      fa: 'تمیز، روشن، کمی مرکبات',
      de: 'Klar, frisch, leicht zitrusartig',
      ar: 'نظيف، منعش، حمضيات خفيفة',
    },
    category: 'snacks',
    ingredients: [
      { en: 'Edamame', fa: 'ادامامه', de: 'Edamame', ar: 'إدامامي' },
      { en: 'Sea salt', fa: 'نمک دریا', de: 'Meersalz', ar: 'ملح بحر' },
      { en: 'Yuzu', fa: 'یوزو', de: 'Yuzu', ar: 'يوزو' },
    ],
    price: 8,
    rating: 4.6,
    calories: 180,
    protein: 14,
    prepMinutes: 8,
    spicyLevel: 0,
    labels: ['bestSeller'],
    imageUrl: img('photo-1582878826629-29b7ad1cdc43'),
  },
  {
    code: 'AP-003',
    name: {
      en: 'Tuna tartare',
      fa: 'تارتار تن',
      de: 'Thunfisch-Tatar',
      ar: 'تارتار تونة',
    },
    description: {
      en: 'Hand-cut tuna, avocado, soy-citrus dressing.',
      fa: 'تن خردشده، آووکادو، سس سویا-مرکبات.',
      de: 'Handgeschnittener Thunfisch, Avocado, Soja-Zitrus-Dressing.',
      ar: 'تونة مقطعة يدوياً، أفوكادو، تتبيلة صويا وحمضيات.',
    },
    taste: {
      en: 'Ocean-fresh, creamy, sharp citrus',
      fa: 'تازه دریایی، خامه‌ای، مرکبات تند',
      de: 'Meeresfrisch, cremig, scharfe Zitrusnote',
      ar: 'طازج بحري، كريمي، حمضيات حادة',
    },
    category: 'appetizers',
    ingredients: [
      { en: 'Tuna', fa: 'تن', de: 'Thunfisch', ar: 'تونة' },
      { en: 'Avocado', fa: 'آووکادو', de: 'Avocado', ar: 'أفوكادو' },
      { en: 'Soy', fa: 'سویا', de: 'Soja', ar: 'صويا' },
      { en: 'Citrus', fa: 'مرکبات', de: 'Zitrus', ar: 'حمضيات' },
    ],
    price: 22,
    rating: 4.9,
    calories: 310,
    protein: 24,
    prepMinutes: 15,
    spicyLevel: 1,
    labels: ['chefChoice', 'bestSeller'],
    imageUrl: img('photo-1579584425555-c3ce17fd4351'),
  },
  {
    code: 'MC-004',
    name: {
      en: 'Miso-glazed salmon',
      fa: 'سالمون لعاب میسو',
      de: 'Lachs mit Miso-Glasur',
      ar: 'سلمون بصلصة الميسو',
    },
    description: {
      en: 'Charred edges, sweet miso, pickled cucumber.',
      fa: 'لبه‌های برشته، میسوی شیرین، خیار ترشی.',
      de: 'Angeflämmte Ränder, süßes Miso, eingelegte Gurke.',
      ar: 'حواف محمّصة، ميسو حلو، خيار مخلل.',
    },
    taste: {
      en: 'Umami-rich, caramelized, cool crunch',
      fa: 'اومامی غنی، کاراملی، ترد خنک',
      de: 'Umami-reich, karamellisiert, kühler Crunch',
      ar: 'أومامي غني، كراميل، قرمشة باردة',
    },
    category: 'mainCourse',
    ingredients: [
      { en: 'Salmon', fa: 'سالمون', de: 'Lachs', ar: 'سلمون' },
      { en: 'Miso', fa: 'میسو', de: 'Miso', ar: 'ميسو' },
      { en: 'Cucumber', fa: 'خیار', de: 'Gurke', ar: 'خيار' },
      { en: 'Rice', fa: 'برنج', de: 'Reis', ar: 'أرز' },
    ],
    price: 28,
    rating: 4.9,
    calories: 540,
    protein: 38,
    prepMinutes: 22,
    spicyLevel: 0,
    labels: ['todaysSpecial', 'bestSeller'],
    imageUrl: img('photo-1467003909585-2f8a72700288'),
  },
  {
    code: 'MC-005',
    name: {
      en: 'Spicy tuna roll',
      fa: 'رول تن تند',
      de: 'Scharfe Thunfischrolle',
      ar: 'رول تونة حار',
    },
    description: {
      en: 'Sesame rice, chili mayo, crisp cucumber core.',
      fa: 'برنج کنجدی، مایو فلفل، هسته خیار ترد.',
      de: 'Sesamreis, Chili-Mayo, knackiger Gurkenkern.',
      ar: 'أرز بالسمسم، مايو حار، قلب خيار مقرمش.',
    },
    taste: {
      en: 'Fiery, creamy, refreshing finish',
      fa: 'تند، خامه‌ای، پایان خنک',
      de: 'Scharf, cremig, erfrischendes Finale',
      ar: 'حار، كريمي، ختام منعش',
    },
    category: 'mainCourse',
    ingredients: [
      { en: 'Tuna', fa: 'تن', de: 'Thunfisch', ar: 'تونة' },
      { en: 'Chili mayo', fa: 'مایو فلفل', de: 'Chili-Mayo', ar: 'مايو حار' },
      { en: 'Cucumber', fa: 'خیار', de: 'Gurke', ar: 'خيار' },
      { en: 'Nori', fa: 'نوری', de: 'Nori', ar: 'نوري' },
    ],
    price: 18,
    rating: 4.7,
    calories: 380,
    protein: 22,
    prepMinutes: 14,
    spicyLevel: 3,
    labels: ['new'],
    imageUrl: img('photo-1579871494447-9811cf80d66c'),
  },
  {
    code: 'MC-006',
    name: {
      en: 'Wagyu donburi',
      fa: 'دانبوری واگیو',
      de: 'Wagyu-Donburi',
      ar: 'دونبوري واغيو',
    },
    description: {
      en: 'Seared wagyu, soft egg, scallion oil over rice.',
      fa: 'واگیوی سرخ‌شده، تخم‌مرغ نرم، روغن پیازچه روی برنج.',
      de: 'Angebratenes Wagyu, weiches Ei, Frühlingszwiebelöl auf Reis.',
      ar: 'واغيو محمر، بيض طري، زيت بصل أخضر فوق الأرز.',
    },
    taste: {
      en: 'Buttery beef, aromatic oil, deep savor',
      fa: 'گوشت کره‌ای، روغن معطر، طعم عمیق',
      de: 'Buttriges Rind, aromatisches Öl, tiefe Würze',
      ar: 'لحم زبدي، زيت عطري، مذاق عميق',
    },
    category: 'mainCourse',
    ingredients: [
      { en: 'Wagyu', fa: 'واگیو', de: 'Wagyu', ar: 'واغيو' },
      { en: 'Egg', fa: 'تخم‌مرغ', de: 'Ei', ar: 'بيض' },
      { en: 'Scallion', fa: 'پیازچه', de: 'Frühlingszwiebel', ar: 'بصل أخضر' },
      { en: 'Rice', fa: 'برنج', de: 'Reis', ar: 'أرز' },
    ],
    price: 42,
    rating: 5,
    calories: 680,
    protein: 36,
    prepMinutes: 20,
    spicyLevel: 1,
    labels: ['limited', 'chefChoice'],
    imageUrl: img('photo-1544025162-d76694265947'),
  },
  {
    code: 'DS-007',
    name: {
      en: 'Matcha soft serve',
      fa: 'بستنی نرم ماچا',
      de: 'Matcha Soft Serve',
      ar: 'آيس كريم ماتشا طري',
    },
    description: {
      en: 'Ceremonial matcha swirl with kinako dust.',
      fa: 'گرداب ماچای تشریفاتی با پودر کیناکو.',
      de: 'Zeremonielles Matcha-Swirl mit Kinako-Staub.',
      ar: 'دوامة ماتشا احتفالية مع غبار كيناكو.',
    },
    taste: {
      en: 'Bitter-sweet green, toasted soybean',
      fa: 'سبز تلخ‌شیرین، سویای بوداده',
      de: 'Bitter-süßes Grün, geröstete Sojabohne',
      ar: 'أخضر مرّ حلو، فول صويا محمص',
    },
    category: 'desserts',
    ingredients: [
      { en: 'Matcha', fa: 'ماچا', de: 'Matcha', ar: 'ماتشا' },
      { en: 'Milk', fa: 'شیر', de: 'Milch', ar: 'حليب' },
      { en: 'Kinako', fa: 'کیناکو', de: 'Kinako', ar: 'كيناكو' },
    ],
    price: 11,
    rating: 4.8,
    calories: 290,
    protein: 6,
    prepMinutes: 5,
    spicyLevel: 0,
    labels: ['new', 'todaysSpecial'],
    imageUrl: img('photo-1563805042-7684c019e1cb'),
  },
  {
    code: 'DS-008',
    name: {
      en: 'Yuzu cheesecake',
      fa: 'چیزکیک یوزو',
      de: 'Yuzu-Käsekuchen',
      ar: 'تشيز كيك يوزو',
    },
    description: {
      en: 'Light cream cheese, bright yuzu curd, sable base.',
      fa: 'کرم‌چیز سبک، کارد یوزوی روشن، پایه سابله.',
      de: 'Leichter Frischkäse, helles Yuzu-Curd, Sablé-Boden.',
      ar: 'جبن كريمي خفيف، كوّة يوزو مشرقة، قاعدة سابليه.',
    },
    taste: {
      en: 'Tangy, creamy, delicate citrus perfume',
      fa: 'ترش‌مزه، خامه‌ای، عطر مرکبات ظریف',
      de: 'Herb, cremig, zartes Zitrusparfüm',
      ar: 'لاذع، كريمي، عطر حمضيات رقيق',
    },
    category: 'desserts',
    ingredients: [
      { en: 'Cream cheese', fa: 'کرم‌چیز', de: 'Frischkäse', ar: 'جبن كريمي' },
      { en: 'Yuzu', fa: 'یوزو', de: 'Yuzu', ar: 'يوزو' },
      { en: 'Butter', fa: 'کره', de: 'Butter', ar: 'زبدة' },
    ],
    price: 13,
    rating: 4.7,
    calories: 360,
    protein: 7,
    prepMinutes: 0,
    spicyLevel: 0,
    labels: ['bestSeller'],
    imageUrl: img('photo-1533134242443-d4fd215305ad'),
  },
  {
    code: 'DR-009',
    name: {
      en: 'Yuzu soda',
      fa: 'سودا یوزو',
      de: 'Yuzu-Soda',
      ar: 'صودا يوزو',
    },
    description: {
      en: 'Sparkling citrus with a pinch of salt.',
      fa: 'مرکبات گازدار با کمی نمک.',
      de: 'Spritzige Zitrusnote mit einer Prise Salz.',
      ar: 'حمضيات فوارة مع رشة ملح.',
    },
    taste: {
      en: 'Zesty, sparkling, palate-cleansing',
      fa: 'تندِ مرکبات، گازدار، پاک‌کننده کام',
      de: 'Spritzig, prickelnd, gaumenreinigend',
      ar: 'لاذع، فوار، ينظّف الحنك',
    },
    category: 'drinks',
    ingredients: [
      { en: 'Yuzu', fa: 'یوزو', de: 'Yuzu', ar: 'يوزو' },
      { en: 'Soda', fa: 'سودا', de: 'Soda', ar: 'صودا' },
      { en: 'Salt', fa: 'نمک', de: 'Salz', ar: 'ملح' },
    ],
    price: 7,
    rating: 4.5,
    calories: 60,
    protein: 0,
    prepMinutes: 3,
    spicyLevel: 0,
    labels: ['todaysSpecial'],
    imageUrl: img('photo-1513558161293-cdaf765ed2fd'),
  },
  {
    code: 'DR-010',
    name: {
      en: 'Hojicha latte',
      fa: 'لاته هوجیچا',
      de: 'Hojicha-Latte',
      ar: 'لاتيه هوجيتشا',
    },
    description: {
      en: 'Roasted tea, steamed milk, amber foam.',
      fa: 'چای بوداده، شیر بخارزده، فوم کهربایی.',
      de: 'Gerösteter Tee, aufgeschäumte Milch, bernsteinfarbener Schaum.',
      ar: 'شاي محمّص، حليب مبخّر، رغوة كهرمانية.',
    },
    taste: {
      en: 'Nutty roast, soft sweetness',
      fa: 'برشته مغزدار، شیرینی نرم',
      de: 'Nussige Röstnote, sanfte Süße',
      ar: 'تحميص بندقي، حلاوة ناعمة',
    },
    category: 'drinks',
    ingredients: [
      { en: 'Hojicha', fa: 'هوجیچا', de: 'Hojicha', ar: 'هوجيتشا' },
      { en: 'Milk', fa: 'شیر', de: 'Milch', ar: 'حليب' },
    ],
    price: 9,
    rating: 4.6,
    calories: 140,
    protein: 5,
    prepMinutes: 6,
    spicyLevel: 0,
    labels: ['chefChoice'],
    imageUrl: img('photo-1576092768241-dec231879fc3'),
  },
  {
    code: 'HL-011',
    name: {
      en: 'Sesame ginger salad',
      fa: 'سالاد کنجد و زنجبیل',
      de: 'Sesam-Ingwer-Salat',
      ar: 'سلطة سمسم وزنجبيل',
    },
    description: {
      en: 'Crunchy greens, toasted sesame, warm ginger dressing.',
      fa: 'سبزی ترد، کنجد بوداده، سس زنجبیل گرم.',
      de: 'Knackiges Grün, gerösteter Sesam, warmes Ingwer-Dressing.',
      ar: 'خضار مقرمشة، سمسم محمّص، تتبيلة زنجبيل دافئة.',
    },
    taste: {
      en: 'Fresh, gingery heat, toasted nuttiness',
      fa: 'تازه، گرمای زنجبیل، مغزدار بوداده',
      de: 'Frisch, ingwerwürzig, geröstete Nussnote',
      ar: 'طازج، حرارة زنجبيل، نكهة محمّصة',
    },
    category: 'healthy',
    ingredients: [
      { en: 'Greens', fa: 'سبزی', de: 'Blattgemüse', ar: 'خضار ورقية' },
      { en: 'Sesame', fa: 'کنجد', de: 'Sesam', ar: 'سمسم' },
      { en: 'Ginger', fa: 'زنجبیل', de: 'Ingwer', ar: 'زنجبيل' },
    ],
    price: 16,
    rating: 4.5,
    calories: 220,
    protein: 8,
    prepMinutes: 10,
    spicyLevel: 1,
    labels: ['new'],
    imageUrl: img('photo-1512621776951-a57141f2eefd'),
  },
  {
    code: 'KD-012',
    name: {
      en: 'Kids rice omelette',
      fa: 'املت برنج کودک',
      de: 'Kinder-Reisomelett',
      ar: 'أومليت أرز للأطفال',
    },
    description: {
      en: 'Mild omelette blanket over ketchup rice.',
      fa: 'پتو املت ملایم روی برنج کچاپ.',
      de: 'Mildes Omelett über Ketchup-Reis.',
      ar: 'غطاء أومليت خفيف فوق أرز بالكاتشب.',
    },
    taste: {
      en: 'Soft, familiar, gently savory',
      fa: 'نرم، آشنا، شور ملایم',
      de: 'Weich, vertraut, sanft herzhaft',
      ar: 'طري، مألوف، مالح بلطف',
    },
    category: 'kids',
    ingredients: [
      { en: 'Egg', fa: 'تخم‌مرغ', de: 'Ei', ar: 'بيض' },
      { en: 'Rice', fa: 'برنج', de: 'Reis', ar: 'أرز' },
      { en: 'Tomato', fa: 'گوجه‌فرنگی', de: 'Tomate', ar: 'طماطم' },
    ],
    price: 12,
    rating: 4.4,
    calories: 390,
    protein: 16,
    prepMinutes: 12,
    spicyLevel: 0,
    labels: [],
    imageUrl: img('photo-1525351484163-7529414344d8'),
  },
  {
    code: 'SS-013',
    name: {
      en: 'Summer peach poke',
      fa: 'پوک هلو تابستانی',
      de: 'Sommerlicher Pfirsich-Poke',
      ar: 'بوكي خوخ صيفي',
    },
    description: {
      en: 'Seasonal peach, tuna, shiso, light ponzu.',
      fa: 'هلوی فصل، تن، شیسو، پونزوی سبک.',
      de: 'Saisonaler Pfirsich, Thunfisch, Shiso, leichter Ponzu.',
      ar: 'خوخ موسمي، تونة، شيسو، بونزو خفيف.',
    },
    taste: {
      en: 'Juicy fruit, herbal cool, bright acid',
      fa: 'میوه آبدار، خنک گیاهی، ترشی روشن',
      de: 'Saftige Frucht, kräuterig-kühl, helle Säure',
      ar: 'فاكهة عصيرية، برودة عشبية، حموضة مشرقة',
    },
    category: 'seasonal',
    ingredients: [
      { en: 'Peach', fa: 'هلو', de: 'Pfirsich', ar: 'خوخ' },
      { en: 'Tuna', fa: 'تن', de: 'Thunfisch', ar: 'تونة' },
      { en: 'Shiso', fa: 'شیسو', de: 'Shiso', ar: 'شيسو' },
      { en: 'Ponzu', fa: 'پونزو', de: 'Ponzu', ar: 'بونزو' },
    ],
    price: 24,
    rating: 4.8,
    calories: 340,
    protein: 26,
    prepMinutes: 15,
    spicyLevel: 0,
    labels: ['limited', 'todaysSpecial'],
    imageUrl: img('photo-1546069901-ba9599a7e63c'),
  },
  {
    code: 'SD-014',
    name: {
      en: 'Gluten-free soba bowl',
      fa: 'کاسه سوبای بدون گلوتن',
      de: 'Glutenfreie Soba-Bowl',
      ar: 'وعاء سوبا خالٍ من الغلوتين',
    },
    description: {
      en: 'Buckwheat noodles, soft egg, greens, light broth.',
      fa: 'نودل گندم سیاه، تخم‌مرغ نرم، سبزی، آبگوشت سبک.',
      de: 'Buchweizennudeln, weiches Ei, Grünzeug, leichte Brühe.',
      ar: 'نودلز الحنطة السوداء، بيض طري، خضار، مرق خفيف.',
    },
    taste: {
      en: 'Earthy noodles, clean broth, soft richness',
      fa: 'نودل خاکی، آبگوشت تمیز، غنای نرم',
      de: 'Erdige Nudeln, klare Brühe, weiche Fülle',
      ar: 'نودلز ترابية، مرق نظيف، غنى ناعم',
    },
    category: 'specialDiet',
    ingredients: [
      { en: 'Soba', fa: 'سوبا', de: 'Soba', ar: 'سوبا' },
      { en: 'Egg', fa: 'تخم‌مرغ', de: 'Ei', ar: 'بيض' },
      { en: 'Greens', fa: 'سبزی', de: 'Grünzeug', ar: 'خضار' },
      { en: 'Broth', fa: 'آبگوشت', de: 'Brühe', ar: 'مرق' },
    ],
    price: 19,
    rating: 4.6,
    calories: 410,
    protein: 20,
    prepMinutes: 16,
    spicyLevel: 0,
    labels: ['chefChoice'],
    imageUrl: img('photo-1569718212165-3a8278d5f624'),
  },
  {
    code: 'AP-015',
    name: {
      en: 'Agedashi tofu',
      fa: 'توفوی آگه‌داشی',
      de: 'Agedashi-Tofu',
      ar: 'توفو أغيداشي',
    },
    description: {
      en: 'Crisp tofu in warm dashi with grated daikon.',
      fa: 'توفوی ترد در داشی گرم با دایکون رنده‌شده.',
      de: 'Knuspriger Tofu in warmem Dashi mit geriebenem Daikon.',
      ar: 'توفو مقرمش في داشي دافئ مع دايكون مبشور.',
    },
    taste: {
      en: 'Crisp shell, silky center, savory broth',
      fa: 'پوسته ترد، مغز ابریشمی، آبگوشت شور',
      de: 'Knusprige Hülle, seidiges Inneres, herzhafte Brühe',
      ar: 'قشرة مقرمشة، قلب حريري، مرق مالح',
    },
    category: 'appetizers',
    ingredients: [
      { en: 'Tofu', fa: 'توفو', de: 'Tofu', ar: 'توفو' },
      { en: 'Dashi', fa: 'داشی', de: 'Dashi', ar: 'داشي' },
      { en: 'Daikon', fa: 'دایکون', de: 'Daikon', ar: 'دايكون' },
    ],
    price: 14,
    rating: 4.5,
    calories: 260,
    protein: 15,
    prepMinutes: 12,
    spicyLevel: 0,
    labels: [],
    imageUrl: img('photo-1546069901-ba9599a7e63c'),
  },
  {
    code: 'SN-016',
    name: {
      en: 'Miso nuts',
      fa: 'آجیل میسو',
      de: 'Miso-Nüsse',
      ar: 'مكسرات الميسو',
    },
    description: {
      en: 'Roasted mixed nuts glazed with white miso.',
      fa: 'آجیل مخلوط بوداده با لعاب میسوی سفید.',
      de: 'Geröstete Mischüsse mit weißer Miso-Glasur.',
      ar: 'مكسرات محمّصة بصلصة ميسو أبيض.',
    },
    taste: {
      en: 'Salty-sweet crunch, deep umami',
      fa: 'ترد شورشیرین، اومامی عمیق',
      de: 'Salzig-süßer Crunch, tiefes Umami',
      ar: 'قرمشة مالحة حلوة، أومامي عميق',
    },
    category: 'snacks',
    ingredients: [
      { en: 'Nuts', fa: 'آجیل', de: 'Nüsse', ar: 'مكسرات' },
      { en: 'Miso', fa: 'میسو', de: 'Miso', ar: 'ميسو' },
      { en: 'Honey', fa: 'عسل', de: 'Honig', ar: 'عسل' },
    ],
    price: 9,
    rating: 4.4,
    calories: 320,
    protein: 10,
    prepMinutes: 0,
    spicyLevel: 1,
    labels: ['bestSeller'],
    imageUrl: img('photo-1599599810769-bcde5a160d32'),
  },
  {
    code: 'BF-017',
    name: {
      en: 'Salmon breakfast set',
      fa: 'ست صبحانه سالمون',
      de: 'Lachs-Frühstücksset',
      ar: 'وجبة إفطار سلمون',
    },
    description: {
      en: 'Grilled salmon, rice, miso soup, pickles.',
      fa: 'سالمون کبابی، برنج، سوپ میسو، ترشی.',
      de: 'Gegrillter Lachs, Reis, Misosuppe, Pickles.',
      ar: 'سلمون مشوي، أرز، شوربة ميسو، مخللات.',
    },
    taste: {
      en: 'Smoky fish, comforting broth, bright pickle',
      fa: 'ماهی دودی، آبگوشت آرامش‌بخش، ترشی روشن',
      de: 'Rauchiger Fisch, wohltuende Brühe, helles Pickle',
      ar: 'سمك مدخّن، مرق مريح، مخلل مشرق',
    },
    category: 'breakfast',
    ingredients: [
      { en: 'Salmon', fa: 'سالمون', de: 'Lachs', ar: 'سلمون' },
      { en: 'Rice', fa: 'برنج', de: 'Reis', ar: 'أرز' },
      { en: 'Miso', fa: 'میسو', de: 'Miso', ar: 'ميسو' },
      { en: 'Pickles', fa: 'ترشی', de: 'Pickles', ar: 'مخللات' },
    ],
    price: 21,
    rating: 4.7,
    calories: 520,
    protein: 32,
    prepMinutes: 18,
    spicyLevel: 0,
    labels: ['chefChoice'],
    imageUrl: img('photo-1467003909585-2f8a72700288'),
  },
  {
    code: 'HL-018',
    name: {
      en: 'High-protein chicken bowl',
      fa: 'کاسه مرغ پروتئینی',
      de: 'High-Protein-Hähnchenbowl',
      ar: 'وعاء دجاج عالي البروتين',
    },
    description: {
      en: 'Grilled chicken, quinoa, greens, lemon tahini.',
      fa: 'مرغ کبابی، کینوا، سبزی، طحینه لیمو.',
      de: 'Gegrilltes Hähnchen, Quinoa, Grünzeug, Zitronen-Tahini.',
      ar: 'دجاج مشوي، كينوا، خضار، طحينة ليمون.',
    },
    taste: {
      en: 'Lean, citrusy, lightly nutty',
      fa: 'کم‌چرب، مرکباتی، کمی مغزدار',
      de: 'Mager, zitrusartig, leicht nussig',
      ar: 'قليل الدهن، حمضي، بندقي خفيف',
    },
    category: 'healthy',
    ingredients: [
      { en: 'Chicken', fa: 'مرغ', de: 'Hähnchen', ar: 'دجاج' },
      { en: 'Quinoa', fa: 'کینوا', de: 'Quinoa', ar: 'كينوا' },
      { en: 'Tahini', fa: 'طحینه', de: 'Tahini', ar: 'طحينة' },
      { en: 'Lemon', fa: 'لیمو', de: 'Zitrone', ar: 'ليمون' },
    ],
    price: 20,
    rating: 4.6,
    calories: 450,
    protein: 42,
    prepMinutes: 18,
    spicyLevel: 1,
    labels: ['new', 'bestSeller'],
    imageUrl: img('photo-1546069901-ba9599a7e63c'),
  },
];

const toItem = (seed: Seed, locale: Locale): MenuItem => ({
  id: `menu-${seed.code.toLowerCase()}`,
  code: seed.code,
  name: seed.name[locale],
  description: seed.description[locale],
  taste: seed.taste[locale],
  category: seed.category,
  ingredients: seed.ingredients.map((entry) => entry[locale]),
  price: seed.price,
  currency: 'USD',
  rating: seed.rating,
  calories: seed.calories,
  protein: seed.protein,
  prepMinutes: seed.prepMinutes,
  spicyLevel: seed.spicyLevel,
  labels: seed.labels,
  imageUrl: seed.imageUrl,
});

const buildLocaleCatalog = (locale: Locale): MenuItem[] =>
  seeds.map((seed) => toItem(seed, locale));

export const menuItemsByLocale: Record<Locale, MenuItem[]> = {
  en: buildLocaleCatalog('en'),
  fa: buildLocaleCatalog('fa'),
  de: buildLocaleCatalog('de'),
  ar: buildLocaleCatalog('ar'),
};
